services:
  app:
    container_name: ${APP_NAME}
    image: ${DOCKERHUB_USERNAME}/lite-board
    ports:
      - "${APP_PORT}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      INVITE_JWT_SECRET: ${INVITE_JWT_SECRET}
    depends_on:
      - redis

  redis:
    image: redis
    container_name: lite-board-redis
    ports:
      - "6379:6379"
