spring:
  application:
    name: TaskTracker

  datasource:
    url: jdbc:mysql://localhost:3306/task_tracker?serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
